
  #.venv/bin/python run_convergence.py plan --sbatch conv.sbatch
  #.venv/bin/python run_convergence.py score
  #.venv/bin/python run_convergence.py table

  #The convergence run: does the world-frame arm ever catch up?
  #
  #Sec. "budget" reports 20 -> 60 epochs at 60 environments as +0.9 for the
  #world frame and +8.0 for the reduction. That is two points per arm, and it
  #answers the objection ("the 30-point gap is an undertraining artefact") with
  #a trend rather than a limit. Neither arm was trained to a plateau, so a
  #referee can still say both arms are simply undertrained and the control has
  #headroom the reduction does not.
  #
  #This script trains both arms at 60 environments until the held-out
  #collision-free rate stops moving, snapshotting on a fixed epoch grid, and
  #scores every snapshot on the SAME never-trained problems the paper uses.
  #Two outcomes, both reportable:
  #  world frame stays flat while the reduction plateaus higher
  #      -> "compute cannot buy what the representation forecloses" becomes a
  #         measured limit rather than an extrapolation from two points
  #  world frame eventually climbs
  #      -> the result is a scaling crossover, not a bottleneck, and Fig. 2
  #         must be relabelled as a fixed-budget comparison
  #
  #LR is deliberately left constant (train_flow.py has no decay schedule). A
  #decayed LR would make every arm flatten at the end and confound "converged"
  #with "the step size went to zero".

import argparse
import itertools
import json
import subprocess
import sys
from pathlib import Path

#The paper's held-out protocol, reproduced exactly: environments 250-299 of the
#300-shard dataset, which no cell trains on, at the 8-step integration budget.
#Changing any of these makes the curve incomparable with the reported numbers.
HOLDOUT_START = 250
HOLDOUT_ENVS = 50
N_PAIRS = 10
N_SAMPLES = 20
STEPS = 8

ARMS = {"control": "ctrl", "treatment": "treat"}


def cells(args):
    for arm, seed in itertools.product(args.arms, args.seeds):
        tag = f"{ARMS[arm]}-e{args.n_envs}-conv-s{seed}"
        yield arm, seed, tag


def train_cmd(args, arm, seed, tag, python=None):
    cmd = [
        python or sys.executable, "train_flow.py",
        "--data", args.data,
        "--n-envs", str(args.n_envs),
        "--env-start", "0",
        "--out", str(Path(args.ckpt_dir) / f"{tag}.pt"),
        "--epochs", str(args.epochs),
        "--batch", str(args.batch),
        "--lr", str(args.lr),
        "--channels", str(args.channels),
        "--n-blocks", str(args.n_blocks),
        "--seed", str(seed),
        "--num-workers", str(args.num_workers),
        "--split-by", "pair",
        "--snapshot-every", str(args.snapshot_every),
        "--resume",
    ]
    if arm == "treatment":
        cmd.append("--reduced")
    if args.amp:
        cmd.append("--amp")
    if args.multi_gpu:
        cmd.append("--multi-gpu")
    if args.wandb:
        cmd += ["--wandb", "--wandb-group", args.group, "--wandb-name", tag]
    return cmd


def cmd_plan(args):
    rows = list(cells(args))
    gpus = [g.strip() for g in args.gpu_ids.split(",") if g.strip()]
    print(f"{len(rows)} cells: {args.arms} x seeds {args.seeds} "
          f"at {args.n_envs} envs, {args.epochs} epochs, "
          f"snapshot every {args.snapshot_every}")
    print(f"{len(gpus)} GPU(s) {gpus}: cells are assigned round-robin and each "
          f"GPU runs its list sequentially\n")
    lines = [" ".join(train_cmd(args, a, s, t)) for a, s, t in rows]
    for i, ((_, _, tag), line) in enumerate(zip(rows, lines)):
        print(f"# gpu {gpus[i % len(gpus)]}  {tag}")
        print(line)

    if not args.launch:
        return

    #One cell per GPU in parallel, rather than DataParallel on one cell at a
    #time: two cells on two GPUs finish in one cell's wall-clock, and this
    #backbone is small enough (2.16M parameters) that DataParallel is
    #launch-bound rather than compute-bound, so splitting a batch across cards
    #buys much less than running two independent cells.
    lanes = []
    for i, g in enumerate(gpus):
        mine = [(rows[j][2], lines[j]) for j in range(i, len(rows), len(gpus))]
        if not mine:
            continue
        body = "\n".join(
            f'  run_cell {g} "{tag}" {line}' for tag, line in mine
        )
        lanes.append(f"(\n{body}\n) &")
    lane_block = "\n".join(lanes)

    script = f"""#!/bin/bash
# Generated by run_convergence.py -- do not edit; regenerate instead.
# Unattended long run: start under nohup/setsid so it survives logout.
#   setsid nohup ./{Path(args.launch).name} > logs/driver.log 2>&1 < /dev/null &
set -uo pipefail
cd "$(dirname "$(readlink -f "$0")")"
mkdir -p logs

# train_flow.py is launched with --resume, so a retry continues from the newest
# snapshot instead of restarting. Retries are BOUNDED: an unbounded loop turns a
# genuine bug into an infinite burn of two GPUs over a weekend.
MAX_TRIES={args.max_tries}

run_cell() {{
  local gpu="$1"; shift
  local tag="$1"; shift
  local try=1
  while [ "$try" -le "$MAX_TRIES" ]; do
    echo "[$(date -Is)] gpu $gpu  $tag  attempt $try/$MAX_TRIES"
    CUDA_VISIBLE_DEVICES="$gpu" "$@" >> "logs/$tag.log" 2>&1 && {{
      echo "[$(date -Is)] gpu $gpu  $tag  done"
      return 0
    }}
    echo "[$(date -Is)] gpu $gpu  $tag  FAILED (attempt $try)"
    try=$((try + 1))
    sleep 60
  done
  echo "[$(date -Is)] gpu $gpu  $tag  GIVING UP after $MAX_TRIES attempts"
  return 1
}}

{lane_block}

wait
echo "[$(date -Is)] all cells finished; score with:"
echo "  {sys.executable} run_convergence.py score"
"""
    p = Path(args.launch)
    p.write_text(script)
    p.chmod(0o755)
    #logs/ must exist BEFORE the launch line: bash opens the redirection target
    #before exec'ing the script, so the script's own mkdir is too late.
    Path("logs").mkdir(exist_ok=True)
    print(f"\nwrote {p}")
    print(f"  mkdir -p logs")
    print(f"  setsid nohup ./{p.name} > logs/driver.log 2>&1 < /dev/null &")
    print(f"  tail -f logs/{rows[0][2]}.log")


def snapshots(args, tag):
    d = Path(args.ckpt_dir)
    return sorted(d.glob(f"{tag}.ep[0-9]*.pt"))


def cmd_score(args):
    out_dir = Path(args.results_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    todo = []
    for arm, seed, tag in cells(args):
        for snap in snapshots(args, tag):
            #K=1 for every arm; K=3 additionally on the reduced arm, which is
            #the only one with a roll gauge to average over (sweep_steps refuses
            #k_fa>1 on a world-frame checkpoint).
            #
            #The pair is the point, not the K=1 number alone. r is flat across
            #training scale while total error falls, so the anti-equivariant
            #share of the REMAINING error should grow as the model improves --
            #i.e. frame averaging should pay more on a better model. At 60
            #environments the measured gain went 34.433 -> 34.517 (+0.08) at 20
            #epochs and 42.400 -> 42.810 (+0.41) at 60. Two points, one of them
            #single-seed. Scoring both K on every snapshot turns that hint into
            #a curve at no extra training cost, and K=1 vs K=3 on one checkpoint
            #is exact -- same weights, same problems, same prior draws -- so the
            #difference carries no seed noise.
            for k in (1, 3) if arm == "treatment" else (1,):
                dest = out_dir / (f"{snap.stem}.json" if k == 1
                                  else f"{snap.stem}-kfa{k}.json")
                if dest.exists() and not args.force:
                    continue
                todo.append((snap, dest, k))
    if not todo:
        print("nothing to score (use --force to rescore)")
        return
    print(f"scoring {len(todo)} snapshots on envs "
          f"[{HOLDOUT_START}, {HOLDOUT_START + HOLDOUT_ENVS}) "
          f"x {N_PAIRS} pairs x {N_SAMPLES} samples at {STEPS} steps\n")
    for snap, dest, k in todo:
        cmd = [
            sys.executable, "sweep_steps.py",
            "--ckpt", str(snap),
            "--data", args.data,
            "--env-start", str(HOLDOUT_START),
            "--n-envs", str(HOLDOUT_ENVS),
            "--n-pairs", str(N_PAIRS),
            "--n-samples", str(N_SAMPLES),
            "--steps", str(STEPS),
            "--seed", str(args.eval_seed),
            "--out-json", str(dest),
        ]
        if k > 1:
            #--residual gives r on the same pass, so the curve carries both the
            #benefit and the quantity that is supposed to bound it
            cmd += ["--k-fa", str(k), "--residual"]
        print(f"  {snap.name}  K={k}")
        r = subprocess.run(cmd)
        if r.returncode != 0:
            print(f"FAILED: {snap.name}", file=sys.stderr)
            if not args.continue_on_error:
                sys.exit(r.returncode)


def cmd_table(args):
    out_dir = Path(args.results_dir)
    curve = {}
    fa = {}   # (arm, seed) -> {epoch: K=3 row}
    for arm, seed, tag in cells(args):
        for path in sorted(out_dir.glob(f"{tag}.ep[0-9]*.json")):
            #"<tag>.ep0010.json" and "<tag>.ep0010-kfa3.json" both land here
            suffix = path.stem.rsplit(".ep", 1)[1]
            epoch_s, _, kfa_s = suffix.partition("-kfa")
            epoch = int(epoch_s)
            row = json.loads(path.read_text())["rows"][0]
            target = fa if kfa_s else curve
            target.setdefault((ARMS[arm], seed), {})[epoch] = row
    if not curve:
        sys.exit(f"no scored snapshots in {out_dir}; run `score` first")

    epochs = sorted({e for v in curve.values() for e in v})
    keys = sorted(curve)
    width = max(len(f"{a}-s{s}") for a, s in keys)
    print(f"\nheld-out collision-free % at {STEPS} steps, "
          f"{args.n_envs} training environments\n")
    print("epoch".rjust(6) + "".join(f"{a}-s{s}".rjust(width + 3) for a, s in keys))
    for e in epochs:
        cellstr = "".join(
            (f"{curve[k][e]['free']:.1f}" if e in curve[k] else "-").rjust(width + 3)
            for k in keys
        )
        print(f"{e:>6}{cellstr}")

    #The question the run exists to answer: is either arm still moving? Read
    #the last two scored points per cell rather than eyeballing the column.
    print("\nlast interval (a plateau is a gain that has gone to zero):")
    for k in keys:
        pts = sorted(curve[k])
        if len(pts) < 2:
            continue
        a, b = pts[-2], pts[-1]
        d = curve[k][b]["free"] - curve[k][a]["free"]
        print(f"  {k[0]}-s{k[1]}: {a} -> {b} epochs, {d:+.1f} points")

    #Does symmetrisation pay more on a better model? r is flat across scale
    #while total error falls, so the anti-equivariant share of the REMAINING
    #error should grow as quality improves. K=1 vs K=3 on one checkpoint is an
    #exact paired comparison -- same weights, same problems, same prior draws --
    #so this delta carries no seed noise, unlike the columns above.
    if fa:
        print("\nframe averaging against model quality "
              "(K=1 vs K=3, paired within checkpoint):")
        print(f"{'epoch':>6}{'K=1':>9}{'K=3':>9}{'delta':>8}{'r':>9}")
        for k in sorted(fa):
            print(f"  {k[0]}-s{k[1]}")
            for e in sorted(fa[k]):
                base = curve.get(k, {}).get(e)
                if base is None:
                    continue
                row = fa[k][e]
                print(f"{e:>6}{base['free']:>9.2f}{row['free']:>9.2f}"
                      f"{row['free'] - base['free']:>+8.2f}"
                      f"{row.get('residual', float('nan')):>9.4f}")

    dest = out_dir / "curve.json"
    dest.write_text(json.dumps(
        {f"{a}-s{s}": {"k1": curve[(a, s)], "k3": fa.get((a, s), {})}
         for a, s in keys}, indent=1, sort_keys=True))
    print(f"\nwrote {dest}")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("mode", choices=["plan", "score", "table"])
    ap.add_argument("--data", type=str, default="data")
    ap.add_argument("--ckpt-dir", type=str, default="checkpoints/conv")
    ap.add_argument("--results-dir", type=str, default="results/conv")
    ap.add_argument("--arms", nargs="+", default=["control", "treatment"],
                    choices=list(ARMS))
    ap.add_argument("--seeds", type=int, nargs="+", default=[0],
                    help="seed 0 answers the question; 1 and 2 give the plateau "
                         "an error bar. Run seed 0 on both arms first")
    ap.add_argument("--n-envs", type=int, default=60,
                    help="60 matches the cell the +8.0/+0.9 result was measured in")
    ap.add_argument("--epochs", type=int, default=300)
    ap.add_argument("--snapshot-every", type=int, default=10)
    ap.add_argument("--batch", type=int, default=1024)
    ap.add_argument("--lr", type=float, default=2e-4)
    ap.add_argument("--channels", type=int, default=128)
    ap.add_argument("--n-blocks", type=int, default=8)
    ap.add_argument("--num-workers", type=int, default=8)
    ap.add_argument("--eval-seed", type=int, default=0)
    ap.add_argument("--amp", action="store_true", default=True)
    ap.add_argument("--no-amp", dest="amp", action="store_false")
    ap.add_argument("--multi-gpu", action="store_true")
    ap.add_argument("--wandb", action="store_true")
    ap.add_argument("--group", type=str, default="convergence")
    ap.add_argument("--force", action="store_true", help="score: rescore existing")
    ap.add_argument("--continue-on-error", action="store_true")
    # launcher (no scheduler: plain SSH, one cell per GPU)
    ap.add_argument("--launch", type=str, default=None,
                    help="plan: write a bash driver to this path")
    ap.add_argument("--gpu-ids", type=str, default="0,1",
                    help="comma-separated CUDA device ids; cells are assigned "
                         "round-robin and each GPU runs its list sequentially")
    ap.add_argument("--max-tries", type=int, default=3,
                    help="attempts per cell before giving up. Each retry "
                         "resumes from the newest snapshot")
    args = ap.parse_args()

    {"plan": cmd_plan, "score": cmd_score, "table": cmd_table}[args.mode](args)


if __name__ == "__main__":
    main()
